[package]
name = "ros"
version = "0.1.0"
authors = ["Lihua Zhao <lihuazhao.cn@windriver.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
